# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia

os:
  - linux
  - osx

julia:
  - 1.3
  - 1.4
  - nightly

notifications:
  email: false

env:
  global:
    - DOCUMENTER_DEBUG=true

matrix:
  allow_failures:
    - julia: nightly

after_success:
  - julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'
  - julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Coveralls.submit(process_folder())'
